services:
  selenium:
    image: selenium/standalone-chrome:3.141.59-20210929
    shm_size: 2gb

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh acceptance_tests/test_server.sh
    environment:
      DJANGO_SETTINGS_MODULE: speakerfight.settings
      SELENIUM_URL: http://selenium:4444/wd/hub
      SELENIUM_BROWSER_URL: http://web:8081
    depends_on:
      - selenium