name: Django Tests

on:
  pull_request:
    branches:
      - trabalho-csi410

  push:
    branches:
      - trabalho-csi410


jobs:
  tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "2.7"


      - name: Install dependencies
        run: |
          pip install -r requirements.txt


      - name: Run Django tests
        run: |
          python manage.py test