name: Django Tests

on:
  pull_request:
    branches:
      - trabalho-csi410

  push:
    branches:
      - trabalho-csi410


jobs:
  tests:

    runs-on: ubuntu-latest

    container:
      image: python:2.7


    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Install dependencies
        run: |
          sed '/fixmydjango==0.3.2/d' requirements.txt > requirements-ci.txt
          pip install -r requirements-ci.txt


      - name: Run Django tests
        env:
          DJANGO_SETTINGS_MODULE: speakerfight.settings
        run: |
          python manage.py test