name: Django Tests

on:
  pull_request:
    branches:
      - trabalho-csi410

  push:
    branches:
      - trabalho-csi410


jobs:
  tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Build Docker environment
        run: |
          docker compose -f docker-compose.local.yml build


      - name: Run Django tests
        run: |
          docker compose -f docker-compose.local.yml run --rm web python manage.py test